kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nodered-ingress
  namespace: nodered
  labels:
    app.kubernetes.io/name: nodered
    app.kubernetes.io/instance: nodered-nodered
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: nodered
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  ingressClassName: nginx
  # defaultBackend:
  #   service:
  #     name: nodered-http
  #     port:
  #       number: 80
  rules:
    - host: dev.nodered.trikorasolutions.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodered
                port:
                  number: 80
# status:
#   loadBalancer:
#     ingress:
#       - ip: 192.168.1.90
