apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nodered
namespace: nodered
commonLabels:
  app: nodered
configurations:
- configuration.yaml
configMapGenerator:
- name: nodered
  envs:
  - nodered-cm.env
secretGenerator:
- name: nodered
  envs:
  - nodered-secret.env
resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml