---
- name: "Install Dolibarr - {{ app_version }}"
  hosts: "{{ k8s_host | default('localhost') }}"
  gather_facts: "{{ gathering_host_info | default('true') | bool == true }}"

  pre_tasks:
    - name: "Validate variables"
      assert:
        that:
          # - "pv_root_folder is defined"
          - "app_name is defined"
          - "app_namespace is defined"
        fail_msg: "Missing required parameters"

  tasks:
    - name: "Template Dolibarr deployment files"
      ansible.builtin.template:
        src: "helm-dolibarr-values.yaml.j2"
        dest: "/tmp/helm-dolibarr-values.yaml"
        mode: '0600'

    - name: "Deploy Dolibarr with Helm"
      kubernetes.core.helm:
        name: dolibarr
        chart_ref: "{% if trikora_helm_project_dir is defined %}{{ trikora_helm_project_dir }}/charts/dolibarr{% else %}trikorasolns/dolibarr{% endif %}"
        release_namespace: "{{ app_namespace }}"
        wait: true
        replace: true
        values_files:
          - /tmp/helm-dolibarr-values.yaml
      register: odoo_helm_res 
...
