---
- name: "Install Apache Nifi"
  hosts: "{{ k8s_host | default ('localhost') }}"
  gather_facts: "{{ gathering_host_info | default('true') | bool == true }}"

  pre_tasks:
    - name: "Validate variables"
      assert:
        that:
          - "app_namespace is defined and (app_namespace | length > 0)"
          - "app_name is defined and (app_name | length > 0)"
        fail_msg: "Missing variables"

  tasks:
    - name: "Template Apache Nifi deployment files (iscsi)"
      ansible.builtin.template:
        src: "helm-apache-nifi-values.yaml.j2"
        dest: "/tmp/helm-pgsql-iscsi-values.yaml"
        mode: '0644'
      when: custom_helm_values_file is not defined and (use_iscsi is not undefined and (use_iscsi | bool))

    - name: "Template Apache Nifi deployment files (default)"
      ansible.builtin.template:
        src: "helm-apache-nifi-values.yaml.j2"
        dest: "/tmp/helm-apache-nifi-values.yaml"
        mode: '0644'
      when: custom_helm_values_file is not defined and (use_iscsi is undefined or not (use_iscsi | bool))

    - name: "Template Apache Nifi deployment files (custom)"
      ansible.builtin.template:
        src: "{{ custom_helm_values_file }}"
        dest: "/tmp/helm-apache-nifi-values.yaml"
        mode: '0644'
      when: custom_helm_values_file is defined      

    - name: "Deploy Apache Nifi with Helm"
      kubernetes.core.helm:
        name: "{{ app_name }}"
        chart_ref: "{% if trikora_helm_project_dir is defined %}{{ trikora_helm_project_dir }}/charts/apache-nifi{% else %}trikorasolns/apache-nifi{% endif %}"
        release_namespace: "{{ app_namespace }}"
        wait: true
        replace: false
        values_files:
          - /tmp/helm-apache-nifi-values.yaml
      register: nifi_helm_install_res 
    
    - name: "Print installation result"
      ansible.builtin.debug:
        var: nifi_helm_install_res
...
